package google

import (
	"github.com/steipete/gogcli/internal/mcp/server"
)

func docsSpecs(p *provider) []server.ToolSpec {
	return []server.ToolSpec{
		{
			Name:        "docs_planBatch",
			Description: "Validate and plan a Docs batch update request without applying changes.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "request"},
				"properties": map[string]any{
					"docId":             map[string]any{"type": "string"},
					"request":           map[string]any{"type": "object"},
					"opId":              map[string]any{"type": "string"},
					"requireRevisionId": map[string]any{"type": "string", "description": "Optional revision ID for optimistic concurrency"},
					"timeoutMs": map[string]any{
						"type": "integer",
					},
					"retries": map[string]any{
						"type": "integer",
					},
					"retryBackoffMs": map[string]any{
						"type": "integer",
					},
				},
			},
			Handler: p.docsPlanBatch,
		}, {
			Name:        "docs_executeBatch",
			Description: "Execute a Docs batch update request.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-heavy",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "request"},
				"properties": map[string]any{
					"docId":             map[string]any{"type": "string"},
					"request":           map[string]any{"type": "object"},
					"opId":              map[string]any{"type": "string"},
					"requireRevisionId": map[string]any{"type": "string", "description": "Optional revision ID for optimistic concurrency"},
					"timeoutMs": map[string]any{
						"type": "integer",
					},
					"retries": map[string]any{
						"type": "integer",
					},
					"retryBackoffMs": map[string]any{
						"type": "integer",
					},
				},
			},
			Handler: p.docsExecuteBatch,
		}, {
			Name:        "docs_sed",
			Description: "Run sed-like find-and-replace expressions on a Google Doc (sedmat).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"expression":     map[string]any{"type": "string"},
					"expressions":    map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					"fileContent":    map[string]any{"type": "string"},
					"dryRun":         map[string]any{"type": "boolean"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsSed,
		}, {
			Name:        "docs_smartEdit",
			Description: "Smart Docs edit: route to batch or sedmat by intent; returns engineSelected, riskLevel, decisionReason.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"intentType":     map[string]any{"type": "string"},
					"request":        map[string]any{"type": "object"},
					"expressions":    map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					"riskTolerance":  map[string]any{"type": "string"},
					"validateOnly":   map[string]any{"type": "boolean"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsSmartEdit,
		}, {
			Name:        "docs_create",
			Description: "Create a new Google Doc. Optionally place it in a Drive folder by parentId (e.g. from drive.ensureFolder).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"title"},
				"properties": map[string]any{
					"title":          map[string]any{"type": "string"},
					"parentId":       map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsCreate,
		}, {
			Name:        "docs_createWithBody",
			Description: "Create a new Google Doc and optionally apply a batchUpdate in one call (faster than create + insertText). Use for creating a doc with initial content and/or formatting. parentId from drive.ensureFolder or drive.searchFiles.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"title"},
				"properties": map[string]any{
					"title":          map[string]any{"type": "string"},
					"parentId":       map[string]any{"type": "string"},
					"request":        map[string]any{"type": "object", "description": "Optional batchUpdate body with 'requests' array (e.g. insertText + updateParagraphStyle)."},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsCreateWithBody,
		}, {
			Name:        "docs_insertText",
			Description: "Insert text at a specific index in a Google Doc.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "text"},
				"properties": map[string]any{
					"docId":        map[string]any{"type": "string"},
					"text":         map[string]any{"type": "string"},
					"index":        map[string]any{"type": "integer"},
					"validateOnly": map[string]any{"type": "boolean"},
					"opId":         map[string]any{"type": "string"},
					"timeoutMs":    map[string]any{"type": "integer"},
					"retries":      map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{
						"type": "integer",
					},
				},
			},
			Handler: p.docsInsertText,
		}, {
			Name:        "docs_deleteRange",
			Description: "Delete a text range in a Google Doc.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "startIndex", "endIndex"},
				"properties": map[string]any{
					"docId":        map[string]any{"type": "string"},
					"startIndex":   map[string]any{"type": "integer"},
					"endIndex":     map[string]any{"type": "integer"},
					"validateOnly": map[string]any{"type": "boolean"},
					"force":        map[string]any{"type": "boolean"},
					"opId":         map[string]any{"type": "string"},
					"timeoutMs":    map[string]any{"type": "integer"},
					"retries":      map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{
						"type": "integer",
					},
				},
			},
			Handler: p.docsDeleteRange,
		}, {
			Name:        "docs_replaceAllText",
			Description: "Replace all text matches in a Google Doc.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "find"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"find":           map[string]any{"type": "string"},
					"replace":        map[string]any{"type": "string"},
					"matchCase":      map[string]any{"type": "boolean"},
					"validateOnly":   map[string]any{"type": "boolean"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsReplaceAllText,
		}, {
			Name:        "docs_appendText",
			Description: "Append text to the end of a Google Doc.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "text"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"text":           map[string]any{"type": "string"},
					"validateOnly":   map[string]any{"type": "boolean"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsAppendText,
		}, {
			Name:        "docs_insertTable",
			Description: "Insert a table in a Google Doc.",
			Tier:        "beta",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"rows":           map[string]any{"type": "integer"},
					"cols":           map[string]any{"type": "integer"},
					"index":          map[string]any{"type": "integer"},
					"validateOnly":   map[string]any{"type": "boolean"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsInsertTable,
		}, {
			Name:        "docs_insertImage",
			Description: "Insert an image into a Google Doc.",
			Tier:        "beta",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "uri"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"uri":            map[string]any{"type": "string"},
					"index":          map[string]any{"type": "integer"},
					"widthPt":        map[string]any{"type": "number"},
					"heightPt":       map[string]any{"type": "number"},
					"validateOnly":   map[string]any{"type": "boolean"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsInsertImage,
		}, {
			Name:        "docs_locatorEdit",
			Description: "Apply anchor or marker-based edits in a Google Doc.",
			Tier:        "beta",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"after":          map[string]any{"type": "string"},
					"insertText":     map[string]any{"type": "string"},
					"betweenStart":   map[string]any{"type": "string"},
					"betweenEnd":     map[string]any{"type": "string"},
					"replaceText":    map[string]any{"type": "string"},
					"validateOnly":   map[string]any{"type": "boolean"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsLocatorEdit,
		}, {
			Name:        "docs_mergeData",
			Description: "Generate Google Docs from a template using JSON data (mail-merge). Use validateOnly to preview operations without creating files.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"templateId", "data"},
				"properties": map[string]any{
					"templateId":       map[string]any{"type": "string"},
					"data":             map[string]any{"type": "array", "items": map[string]any{"type": "object"}, "description": "Array of record objects for merge"},
					"filenameFormat":   map[string]any{"type": "string"},
					"outputFolderId":   map[string]any{"type": "string"},
					"includeTimestamp": map[string]any{"type": "boolean"},
					"validateOnly":     map[string]any{"type": "boolean"},
					"dryRun":           map[string]any{"type": "boolean"},
					"account":          map[string]any{"type": "string"},
				},
			},
			Handler: p.docsMergeData,
		}, {
			Name:        "docs_get",
			Description: "Get Google Doc metadata and revision (thin wrapper around gog docs info). Returns id, name, revisionId, webViewLink.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":   map[string]any{"type": "string"},
					"account": map[string]any{"type": "string"},
				},
			},
			Handler: p.docsGet,
		}, {
			Name:        "docs_cat",
			Description: "Extract plain text from a Google Doc (thin wrapper around gog docs cat). Use maxBytes to limit size; tab or allTabs for multi-tab docs.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":    map[string]any{"type": "string"},
					"maxBytes": map[string]any{"type": "integer", "description": "Max bytes to read (default 2000000)"},
					"tab":      map[string]any{"type": "string", "description": "Tab title or ID to read"},
					"allTabs":  map[string]any{"type": "boolean", "description": "Include all tabs with headers"},
					"account":  map[string]any{"type": "string"},
				},
			},
			Handler: p.docsCat,
		}, {
			Name:        "docs_listTabs",
			Description: "List all tabs in a Google Doc with id, title, index (thin wrapper around gog docs list-tabs).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":   map[string]any{"type": "string"},
					"account": map[string]any{"type": "string"},
				},
			},
			Handler: p.docsListTabs,
		}, {
			Name:        "docs_positionsEnd",
			Description: "Return the append index for a Google Doc (1-based position after last content). Use before docs.insertText or append to know where to insert.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":   map[string]any{"type": "string"},
					"account": map[string]any{"type": "string"},
				},
			},
			Handler: p.docsPositionsEnd,
		}, {
			Name:        "docs_positionsSearch",
			Description: "Search for text in a Google Doc and return startIndex/endIndex ranges (UTF-16). Use for precise insert/delete.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId", "text"},
				"properties": map[string]any{
					"docId":     map[string]any{"type": "string"},
					"text":      map[string]any{"type": "string"},
					"matchCase": map[string]any{"type": "boolean"},
					"account":   map[string]any{"type": "string"},
				},
			},
			Handler: p.docsPositionsSearch,
		}, {
			Name:        "docs_positionsHeadings",
			Description: "Return positions of HEADING_1..HEADING_6 paragraphs in a Google Doc (startIndex, endIndex, style, text).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":   map[string]any{"type": "string"},
					"account": map[string]any{"type": "string"},
				},
			},
			Handler: p.docsPositionsHeadings,
		}, {
			Name:        "docs_export",
			Description: "Export a Google Doc to a file (pdf, docx, or txt). If out is omitted, writes to a temp file and returns path in result.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"docId"},
				"properties": map[string]any{
					"docId":          map[string]any{"type": "string"},
					"format":         map[string]any{"type": "string", "description": "pdf (default), docx, or txt"},
					"out":            map[string]any{"type": "string", "description": "Output path; omit to write to temp and get path in result"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.docsExport,
		},
	}
}
