package google

import (
	"github.com/steipete/gogcli/internal/mcp/server"
)

func driveSpecs(p *provider) []server.ToolSpec {
	return []server.ToolSpec{
		{
			Name:        "drive_ensureFolder",
			Description: "Ensure a folder path exists in Drive; create missing segments.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"path"},
				"properties": map[string]any{
					"path":           map[string]any{"type": "string"},
					"parentId":       map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveEnsureFolder,
		}, {
			Name:        "drive_untrash",
			Description: "Restore a trashed Drive file.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveUntrash,
		}, {
			Name:        "drive_getPermission",
			Description: "Get one permission entry for a Drive file.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "permissionId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"permissionId":   map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveGetPermission,
		}, {
			Name:        "drive_listFiles",
			Description: "List files and folders in a Drive folder (default root). Returns one page (default 25 items) + nextPageToken. For 'how many folders in root' use drive_searchFiles with query mimeType = 'application/vnd.google-apps.folder' and 'root' in parents, rawQuery true, and fetchAllPages: true. Use page or pageToken for next page. Set global=true to list across all accessible files (cannot combine with parentId).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"parentId":      map[string]any{"type": "string"},
					"query":         map[string]any{"type": "string"},
					"max":           map[string]any{"type": "integer"},
					"page":          map[string]any{"type": "string"},
					"pageToken":     map[string]any{"type": "string"},
					"maxResults":    map[string]any{"type": "integer"},
					"pageSize":      map[string]any{"type": "integer"},
					"fetchAllPages": map[string]any{"type": "boolean", "description": "If true, fetch all pages server-side and return totalCount; use for 'how many' or 'count all'."},
					"global":        map[string]any{"type": "boolean"},
					"allDrives": map[string]any{
						"type": "boolean",
					},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveListFiles,
		}, {
			Name:        "drive_searchFiles",
			Description: "Search files and folders in Google Drive. Returns one page (default 25 items) + nextPageToken. For 'how many folders in root' or 'count all X', set fetchAllPages: true to get totalCount in one call without chaining pageToken. Use page or pageToken for next page. For 'list all folders' use query mimeType = 'application/vnd.google-apps.folder' with rawQuery true (and 'root' in parents for root only).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"query"},
				"properties": map[string]any{
					"query":          map[string]any{"type": "string"},
					"rawQuery":       map[string]any{"type": "boolean"},
					"max":            map[string]any{"type": "integer"},
					"page":           map[string]any{"type": "string"},
					"pageToken":      map[string]any{"type": "string"},
					"maxResults":     map[string]any{"type": "integer"},
					"pageSize":       map[string]any{"type": "integer"},
					"fetchAllPages":  map[string]any{"type": "boolean", "description": "If true, fetch all pages server-side and return totalCount (avoids pageToken chaining); use for 'how many' or 'count all'."},
					"allDrives":      map[string]any{"type": "boolean"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveSearchFiles,
		}, {
			Name:        "drive_getFile",
			Description: "Get Drive file metadata.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveGetFile,
		}, {
			Name:        "drive_uploadFile",
			Description: "Upload a local file to Google Drive. Use for backups: localPath is the path on the server where gog runs (e.g. on Linode use a path like /var/backups/file.tar.gz). Optionally set parentId (folder ID), name (Drive filename), or replaceFileId to overwrite an existing file.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-heavy",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"localPath"},
				"properties": map[string]any{
					"localPath": map[string]any{"type": "string", "description": "Path to the file on the server where gog/MCP runs (e.g. /var/backups/backup.tar.gz)"},
					"name":      map[string]any{"type": "string", "description": "Drive filename (default: basename of localPath)"},
					"parentId":  map[string]any{"type": "string", "description": "Drive folder ID to upload into"},
					"replaceFileId": map[string]any{
						"type":        "string",
						"description": "Overwrite this existing Drive file ID (keeps sharing); cannot combine with parentId",
					},
					"mimeType":            map[string]any{"type": "string"},
					"convert":             map[string]any{"type": "boolean"},
					"convertTo":           map[string]any{"type": "string"},
					"keepRevisionForever": map[string]any{"type": "boolean", "description": "Keep this revision forever (e.g. for backup retention)"},
					"account":             map[string]any{"type": "string"},
					"opId":                map[string]any{"type": "string"},
					"timeoutMs":           map[string]any{"type": "integer"},
					"retries":             map[string]any{"type": "integer"},
					"retryBackoffMs":      map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveUploadFile,
		}, {
			Name:        "drive_downloadFile",
			Description: "Download Drive file by ID.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"out":            map[string]any{"type": "string"},
					"format":         map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveDownloadFile,
		}, {
			Name:        "drive_listPermissions",
			Description: "List permissions on a Drive file.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"max":            map[string]any{"type": "integer"},
					"page":           map[string]any{"type": "string"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveListPermissions,
		}, {
			Name:        "drive_listComments",
			Description: "List comments on a Drive file.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "read-fast",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"max":            map[string]any{"type": "integer"},
					"page":           map[string]any{"type": "string"},
					"all":            map[string]any{"type": "boolean"},
					"includeQuoted":  map[string]any{"type": "boolean"},
					"failEmpty":      map[string]any{"type": "boolean"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveListComments,
		}, {
			Name:        "drive_deleteFile",
			Description: "Delete or trash a Drive file.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId"},
				"properties": map[string]any{
					"fileId":         map[string]any{"type": "string"},
					"permanent":      map[string]any{"type": "boolean"},
					"force":          map[string]any{"type": "boolean"},
					"validateOnly":   map[string]any{"type": "boolean", "description": "If true, return planned action without executing"},
					"account":        map[string]any{"type": "string"},
					"opId":           map[string]any{"type": "string"},
					"timeoutMs":      map[string]any{"type": "integer"},
					"retries":        map[string]any{"type": "integer"},
					"retryBackoffMs": map[string]any{"type": "integer"},
				},
			},
			Handler: p.driveDeleteFile,
		}, {
			Name:        "drive_moveFile",
			Description: "Move a Drive file to a different folder (thin wrapper around gog drive move).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "parentId"},
				"properties": map[string]any{
					"fileId":   map[string]any{"type": "string"},
					"parentId": map[string]any{"type": "string", "description": "New parent folder ID"},
					"account":  map[string]any{"type": "string"},
				},
			},
			Handler: p.driveMoveFile,
		}, {
			Name:        "drive_renameFile",
			Description: "Rename a Drive file or folder (thin wrapper around gog drive rename).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "name"},
				"properties": map[string]any{
					"fileId":  map[string]any{"type": "string"},
					"name":    map[string]any{"type": "string", "description": "New file or folder name"},
					"account": map[string]any{"type": "string"},
				},
			},
			Handler: p.driveRenameFile,
		}, {
			Name:        "drive_shareFile",
			Description: "Share a Drive file (add permission). Use to: anyone (link), user (email), or domain. Role: reader or writer.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "to"},
				"properties": map[string]any{
					"fileId":       map[string]any{"type": "string"},
					"to":           map[string]any{"type": "string", "description": "anyone|user|domain"},
					"email":        map[string]any{"type": "string", "description": "Required when to=user"},
					"domain":       map[string]any{"type": "string", "description": "Required when to=domain"},
					"role":         map[string]any{"type": "string", "description": "reader|writer (default reader)"},
					"discoverable": map[string]any{"type": "boolean"},
					"account":      map[string]any{"type": "string"},
				},
			},
			Handler: p.driveShareFile,
		}, {
			Name:        "drive_unshare",
			Description: "Remove a permission from a Drive file (thin wrapper around gog drive unshare). Requires force=true to skip confirmation.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "permissionId"},
				"properties": map[string]any{
					"fileId":       map[string]any{"type": "string"},
					"permissionId": map[string]any{"type": "string"},
					"force":        map[string]any{"type": "boolean"},
					"validateOnly": map[string]any{"type": "boolean", "description": "If true, return planned action without executing"},
					"account":      map[string]any{"type": "string"},
				},
			},
			Handler: p.driveUnshare,
		}, {
			Name:        "drive_createComment",
			Description: "Create a comment on a Drive file (thin wrapper around gog drive comments create). Optional quoted text for Docs.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "content"},
				"properties": map[string]any{
					"fileId":  map[string]any{"type": "string"},
					"content": map[string]any{"type": "string"},
					"quoted":  map[string]any{"type": "string", "description": "Anchor comment to this text (e.g. for Google Docs)"},
					"account": map[string]any{"type": "string"},
				},
			},
			Handler: p.driveCreateComment,
		}, {
			Name:        "drive_deleteComment",
			Description: "Delete a comment on a Drive file (thin wrapper around gog drive comments delete). Requires force=true to skip confirmation.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "commentId"},
				"properties": map[string]any{
					"fileId":       map[string]any{"type": "string"},
					"commentId":    map[string]any{"type": "string"},
					"force":        map[string]any{"type": "boolean"},
					"validateOnly": map[string]any{"type": "boolean", "description": "If true, return planned action without executing"},
					"account":      map[string]any{"type": "string"},
				},
			},
			Handler: p.driveDeleteComment,
		}, {
			Name:        "drive_copyFile",
			Description: "Copy a Drive file to a new name and optionally to a folder (thin wrapper around gog drive copy).",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"fileId", "name"},
				"properties": map[string]any{
					"fileId":   map[string]any{"type": "string"},
					"name":     map[string]any{"type": "string", "description": "New file name"},
					"parentId": map[string]any{"type": "string"},
					"account":  map[string]any{"type": "string"},
				},
			},
			Handler: p.driveCopyFile,
		}, {
			Name:        "drive_bulkExecute",
			Description: "Execute a bounded list of Drive operations (move, rename, share, delete). Use validateOnly to preview without executing. Max 50 operations per call.",
			Tier:        "ga",
			Version:     "v1",
			PolicyClass: "write-safe",
			InputSchema: map[string]any{
				"type":     "object",
				"required": []string{"operations"},
				"properties": map[string]any{
					"operations":   map[string]any{"type": "array", "items": map[string]any{"type": "object"}, "description": "List of { op: move|rename|share|delete, fileId, ... }"},
					"validateOnly": map[string]any{"type": "boolean"},
					"account":      map[string]any{"type": "string"},
				},
			},
			Handler: p.driveBulkExecute,
		},
	}
}
